---
- name: install nginx repository
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: check httpd status
  command: systemctl status httpd
  register: httpd_status
  ignore_errors: true

- name: disable httpd
  service: 
    name: httpd
    state: stopped
  when: httpd_status.stdout.find('active') != -1

- name: start and enanle nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: create vhost directory
  file:
    path: /var/www/vhosts/{{ domain_name }}/public_html
    state: directory
    mode: "0755"
    recurse: yes

- name: copy index.html
  template:
    src: ../templates/index.html
    dest: /var/www/vhosts/{{ domain_name }}/public_html

- name: copy vhost.conf
  template:
    src: ../templates/vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ domain_name }}.conf
  notify:
    - restart nginx